go get github.com/gin-gonic/gin
go get github.com/mackerelio/go-osstat
go get github.com/spf13/cobra
go get k8s.io/apimachinery@v0.17.0
go get k8s.io/kube-scheduler@v0.17.0
go get github.com/miekg/dns
go get k8s.io/code-generator@v0.17.0
go get k8s.io/api@v0.17.0
go get k8s.io/client-go@v0.17.0
go get google.golang.org/grpc
go get github.com/gorilla/mux
