apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cloudedgeservices.k8s.schwarzeni.com
spec:
  group: k8s.schwarzeni.com
  version: v1alpha1
  names:
    kind: CloudEdgeService
    plural: cloudedgeservices
  scope: Namespaced
